config-version: 7

entities:
  autospawn-ticks: 200
  despawn-ticks: 8000
  worlds-spawning-disabled: "exampleworld1, exampleworld2"

autospawn:
  bat: true
  blaze: true
  chicken: true
  cod: true
  cow: true
  creeper: true
  dolphin: true
  donkey: true
  enderman: true
  ghast: true
  husk: true
  horse: true
  magmacube: true
  mooshroom: true
  ocelot: true
  parrot: true
  pig: true
  polarbear: true
  pufferfish: true
  rabbit: true
  salmon: true
  sheep: true
  skeleton: true
  slime: true
  spider: true
  squid: true
  stray: true
  tropicalfish: true
  turtle: true
  witch: true
  witherskeleton: true
  wolf: true
  zombie: true
  zombiepigman: true
