config-version: 8

entities:
  autospawn-ticks: 200
  despawn-ticks: 6000
  worlds-spawning-disabled: "exampleworld1, exampleworld2"

autospawn:
  bat: 2
  blaze: 2
  chicken: 2
  cod: 2
  cow: 2
  creeper: 2
  dolphin: 2
  donkey: 2
  enderman: 2
  ghast: 2
  husk: 2
  horse: 2
  magmacube: 2
  mooshroom: 2
  ocelot: 2
  parrot: 2
  pig: 2
  polarbear: 2
  pufferfish: 2
  rabbit: 2
  salmon: 2
  sheep: 2
  skeleton: 2
  slime: 2
  spider: 2
  squid: 2
  stray: 2
  tropicalfish: 2
  turtle: 2
  witch: 2
  witherskeleton: 2
  wolf: 2
  zombie: 2
  zombiepigman: 2
