config-version: 6

entities:
  auto-spawn-tick: 200
  worlds-spawn-disabled: "exampleworld1,exampleworld2"
  despawn-entities: true
  despawn-ticks: 10000

max-spawns:
  bat: 0
  blaze: 0
  chicken: 1
  cod: 0
  cow: 1
  creeper: 0
  dolphin: 0
  donkey: 0
  enderman: 0
  ghast: 0
  husk: 0
  horse: 0
  magmacube: 0
  mooshroom: 0
  ocelot: 0
  parrot: 0
  pig: 1
  polarbear: 0
  pufferfish: 0
  rabbit: 0
  salmon: 0
  sheep: 1
  skeleton: 0
  slime: 0
  spider: 0
  squid: 0
  stray: 0
  tropicalfish: 0
  turtle: 0
  witch: 0
  witherskeleton: 0
  wolf: 0
  zombie: 0
  zombiepigman: 0