name: MobPlugin
main: de.kniffo80.mobplugin.MobPlugin
version: "1.0"
api: ["1.0.0"]

load: STARTUP
author: kniffo80, matt404, augesrob, PetteriM1
description: Mob plugin for Nukkit
website: https://github.com/Nukkit-coders/mob-plugin
commands: []

commands:
  mob spawn:
    description: Spawn a simple mob to the player, that is using this command
    aliases: ["mob"]
    usage: "/mob spawn <mob_name>"
    permission: mob-plugin.command
  mob removeall:
    description: Remove all living mobs
    aliases: ["mob removeall"]
    usage: "/mob removeall"
    permission: mob-plugin.command
  mob removeitems:
    description: Remove all items from ground
    aliases: ["mob removeitems"]
    usage: "/mob removeitems"
    permission: mob-plugin.command    
permissions:
  mob-plugin.command:
    description: ""
    default: op
